/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package topsis;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import static topsis.Tambah_alternatif.btn_simpan;

/**
 *
 * @author hanif
 */
public class TambahNilai extends javax.swing.JDialog {

    private static int id;

    public TambahNilai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadAlternatif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_batal = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        alternatif = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        c3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NAMA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TAMBAH NILAI");

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_simpan.setText("TAMBAH");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        alternatif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        alternatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternatifActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("IPK");

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<= 3,0", "3,01 - 3,40", "3,41 - 3,60", "3,61 - 3,80", "3,81 - 4,0" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TES PENGETAHUAN UMUM");

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Sangat Buruk", "2 -  Buruk", "3 - Cukup", "4 - Baik", "5 - Sangat Baik" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Sangat Buruk", "2 -  Buruk", "3 - Cukup", "4 - Baik", "5 - Sangat Baik" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("TES B. INGGRIS");

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<= 3 Sertifikat", "4 - 6 Sertifikat", "7 - 8 Sertifikat", "9 - 10 Sertifikat", "10+ Sertifikat" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("SERTIFIKASI");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("LOMBA");

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 tidak pernah", "1 Submit", "2 Finalis", "3 Juara 3", "4 Juara 2", "5 Juara 1" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alternatif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_batal)
                        .addGap(37, 37, 37)
                        .addComponent(btn_simpan)
                        .addGap(31, 31, 31)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(alternatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal)
                    .addComponent(btn_simpan))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        var cek = btn_simpan.getText();

        var alt = alternatif.getSelectedItem();
        var C1 = c1.getSelectedIndex() + 1;
        var C2 = c2.getSelectedIndex() + 1;
        var C3 = c3.getSelectedIndex() + 1;
        var C4 = c4.getSelectedIndex() + 1;
        var C5 = c5.getSelectedIndex(); // Sesuaikan +1 jika memang perlu

        try {
            Connection k = Koneksi.Go();
            Statement s = k.createStatement();
            if ("TAMBAH".equals(cek)) {
                String q = "SELECT id FROM alternatif WHERE nama = '" + alt + "'";
                ResultSet r = s.executeQuery(q);
                if (r.next()) {
                    alt = r.getString("id");
                }

                String nilai = "INSERT INTO alt_nilai (alt_id, c1, c2, c3, c4, c5) VALUES "
                        + "('" + alt + "', '" + C1 + "', '" + C2 + "', '" + C3 + "', '" + C4 + "', '" + C5 + "')";
                s.executeUpdate(nilai);
            } else {
                String query = "UPDATE alt_nilai SET "
                        + "c1 = '" + C1 + "', "
                        + "c2 = '" + C2 + "', "
                        + "c3 = '" + C3 + "', "
                        + "c4 = '" + C4 + "', "
                        + "c5 = '" + C5 + "' "
                        + "WHERE alt_id = '" + id + "'";
                s.executeUpdate(query);
            }

            setVisible(false);
            MainApp.loadNilai();
            MainApp.topsis();
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_batalActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void alternatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternatifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternatifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TambahNilai dialog = new TambahNilai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> alternatif;
    private javax.swing.JButton btn_batal;
    private static javax.swing.JButton btn_simpan;
    private static javax.swing.JComboBox<String> c1;
    private static javax.swing.JComboBox<String> c2;
    private static javax.swing.JComboBox<String> c3;
    private static javax.swing.JComboBox<String> c4;
    private static javax.swing.JComboBox<String> c5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void loadAlternatif() {
        try {
            Connection k = Koneksi.Go();
            Statement st = k.createStatement();
            String query = "SELECT nama, id FROM alternatif";
            ResultSet rs = st.executeQuery(query);

            List<String> AlternatifList = new ArrayList<>();
            while (rs.next()) {
                var nama = rs.getString("nama");
                var id = rs.getInt("id");

                Statement st2 = k.createStatement();
                String q2 = "SELECT alt_id FROM alt_nilai WHERE alt_id = " + id;
                ResultSet r2 = st2.executeQuery(q2);

                if (!r2.next()) {
                    AlternatifList.add(nama); // Add to list if no entry found in alt_nilai
                }

                r2.close();
                st2.close();
            }

            alternatif.removeAllItems();

            // Add items to comboBoxKriteria
            for (String alternatifs : AlternatifList) {
                alternatif.addItem(alternatifs);
            }

            rs.close();
            st.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void edit(String nama) {
        if (nama != null) {
            try {
                Connection k = Koneksi.Go();
                Statement s = k.createStatement();
                var getid = "SELECT * FROM alternatif WHERE NAMA = '" + nama + "' ";
                ResultSet r = s.executeQuery(getid);
                if (r.next()) {
                    id = r.getInt("id");
                    alternatif.removeAllItems();
                    alternatif.addItem(r.getString("nama"));
                    alternatif.setSelectedItem(r.getString("nama"));
                    var getnilai = "SELECT * FROM alt_nilai WHERE alt_id = '" + id + "' ";
                    ResultSet r2 = s.executeQuery(getnilai);
                    while (r2.next()) {
                        c1.setSelectedIndex(r2.getInt("c1") - 1);
                        c2.setSelectedIndex(r2.getInt("c2") - 1); // Indeks JComboBox mulai dari 0
                        c3.setSelectedIndex(r2.getInt("c3") - 1);
                        c4.setSelectedIndex(r2.getInt("c4") - 1);
                        c5.setSelectedIndex(r2.getInt("c5"));
                    }
                    r2.close();
                }
                btn_simpan.setText("SIMPAN");
                jLabel5.setText("EDIT NILAI");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
